change workflow

diff --git a/.github/workflows/tabs-counter.yaml b/.github/workflows/tabs-counter.yaml
--- a/.github/workflows/tabs-counter.yaml
+++ b/.github/workflows/tabs-counter.yaml
@@ -1,33 +1,36 @@
-name: CI
+name: Gets all changed files, find tabs, generate report
 
-on:
-  pull_request:
-    branches:
-      - main
+on: [pull_request]
 
 jobs:
-  build:
-    runs-on: ubuntu-latest  # windows-latest | macos-latest
-    name: Test changed-files
+  find-changed-files:
+    runs-on: ubuntu-latest
+    outputs:
+      files: ${{ steps.files.outputs.all }}
     steps:
-      - uses: actions/checkout@v2
-        with:
-          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
-
       - name: Get changed files
-        id: changed-files
-        uses: tj-actions/changed-files@v14.1
+        uses: jitterbit/get-changed-files@v1
+        id: files
+        with:
+          format: 'json'
+          token: ${{ secrets.GITHUB_TOKEN }}
       - run: |
           echo "List of changed files got succesfully"
-          echo "${{ steps.changed-files.outputs.all_changed_files }}"  
-
-      - name: List all changed files
+          echo "${{ steps.files.outputs.all }}"
+  find-tabs:
+    needs: find-changed-files
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        changed-files: ${{fromJson(needs.find-changed-files.outputs.files)}}
+      fail-fast: false
+    steps:
+      - uses: actions/checkout@v2.1.0
+      - name: Find tabs
         run: |
-          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
-            echo "$file was changed"  >> ${file}.log
-          done
-
+          echo "${{matrix.changed-files}}"
+          cat ${{matrix.changed-files}} | grep -P "\t" > ${{matrix.changed-files}}.log 2>&1 || echo "Tabs not found"
       - name: Upload report
         uses: actions/upload-artifact@v2
         with:
-          path: ${file}.log
+          path: ${{ matrix.changed-files }}.log
